#!/bin/sh

export SHELL=/usr/bin/zsh
sed -r 's/^-- /\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n##############################/' *.pres | sed 's/^/ /' | less -p' ##############################' -M
